mqtt:
  brokers:
    client1:
      broker: tcp://192.168.2.201:1883
      username: mqtest01
      password: 123456
      maxInflight: 1000
      clientId: mqtt-spring-test-node2 # 客户端ID，必须配置，且在同一broker中唯一，表明节点身份
      connectTimeout: 10
      timeTowait: 2
      reConnectDelay: 10

    node1:
      broker: tcp://inverter.bsiotportal.com:2883
      #      username: bs_cloud_v2
      username: iotmq-UEaBrPh2GSk2zJ
      #      password: Tu34PR4MewTESFvn
      password: jiale@123
      maxInflight: 1000
      clientId: test_relay_12
      connectTimeout: 10
      timeToWait: 3
      reConnectDelay: 10
      #logging:
      #  level:
      #com.github.neu.*: debug
logging:
  level:
    com:
      github:
        neu.*: debug
