mqtt:
  clients: # node1 node2 节点名可以自定义名称
    client1:
      broker: tcp://192.168.2.201:1883
      username: mq01
      password: 123456
      maxInflight: 1000

    node1:
      broker: tcp://192.168.2.201:1883
      username: mq01
      password: 123456
      maxInflight: 1000
